### ISSUE TITLE
no required module provides package main.go; to add it: go get main.go

### ISSUE THREAD

**Issue by gannicusleon** [mylxsw/aidea-server#1]
执行 go build -o build/debug/aidea-server main.go 时报错

no required module provides package main.go; to add it:
	go get main.go

**Comment by mylxsw** [comment]
不好意思，文档写错了，应该是 

```bash
go build -o build/debug/aidea-server cmd/main.go
```

**main.go** 移动到 **cmd/main.go** 了。
