### ISSUE TITLE
部分接口存在跨域错误

### ISSUE THREAD

**Issue by luoyou** [mylxsw/aidea-server#19]
之前所有的接口均会报跨域错误，研究了下框架的问题，新增了代码`mw.CORS("*"),`（加完了发现代码里面本身就是解决跨域的地方，即第二个红框圈出来的地方），注册阶段的跨域错误解决了，但是需要登录的接口仍然存在跨域错误。
![image](https://github.com/mylxsw/aidea-server/assets/2688923/ff990b44-b68f-4e0b-8cf0-dbc8ba08176e)

![image](https://github.com/mylxsw/aidea-server/assets/2688923/6c7ed99c-64e5-4e5e-a01b-ac774727d98a)

**Comment by mylxsw** [comment]
切到 develop 分支哈，这个问题上周就解决了，没有合并主分支

**Comment by luoyou** [comment]
![image](https://github.com/mylxsw/aidea-server/assets/2688923/a421909b-a537-4674-b2d8-1f246fd7c9d4)
切到develop分支，配置了enable_cors: true，所有接口仍然报跨域错误。
![image](https://github.com/mylxsw/aidea-server/assets/2688923/75535edc-40e7-4212-b208-d6a4053891a4)

**Comment by mylxsw** [comment]
配置写错了，是中划线，不是下划线 

enable-cors

**Comment by luoyou** [comment]
问题已解决，谢谢，这才发现在config.go中指定的yaml配置都是下划线，直接复制过来了
