### ISSUE TITLE
图片转视频功能报文件不存在错误

### ISSUE THREAD

**Issue by happyue** [mylxsw/aidea-server#43]
BuildImageToVideoCompletionHandler 函数中， 		
targetImage, err := uploader.DownloadRemoteFile(ctx, payload.Image)
if err != nil {
	log.WithFields(log.Fields{"payload": payload}).Errorf("download remote file failed: %s", err)
	panic(err)
}
报错，文件不存在。 
查看七牛云，有原始文件，没有resize之后的tagetimage， ImageToVideo函数中resize之后，有上传七牛吗？

**Comment by mylxsw** [comment]
需要在七牛云再添加 3 个新的图片样式 [部署指南](https://github.com/mylxsw/aidea-server/blob/main/docs/deploy.md)

<img width="884" alt="image" src="https://github.com/mylxsw/aidea-server/assets/2330911/6688d644-1491-45fe-8726-9752c98a38af">
