### ISSUE TITLE
本地客户端一直连不上本地启动的服务端

### ISSUE THREAD

**Issue by qyazhou** [mylxsw/aidea-server#51]
服务端成功启动
{"module":"main","level_name":"INFO","level":7,"context":{},"message":"服务启动成功，监听地址为 :8080","datetime":"2024-03-02T21:06:51+09:00"}
客户端也配置好了服务器地址
/// 默认 API 服务器地址
/// 注意：当你使用自己的服务器时，请修改该地址为你自己的服务器地址
//const defaultAPIServerURL = 'https://ai-api.aicode.cc';
const defaultAPIServerURL = 'http://127.0.0.1:8080';

/// API 服务器地址
String get apiServerURL {
  var url = const String.fromEnvironment(
    'API_SERVER_URL',
    defaultValue: defaultAPIServerURL,
  );

但是客户端的请求一直连不上服务器，客户端报错信息如下图：
![client](https://github.com/mylxsw/aidea-server/assets/8603086/baa93c58-6e2e-4439-ac94-9903532e4435)

**Comment by qyazhou** [comment]
网络接口报错信息如下：
![image](https://github.com/mylxsw/aidea-server/assets/8603086/fb81c7be-2a73-4e95-a94d-38bf04f426ab)

**Comment by mylxsw** [comment]
应该是跨域问题，在服务端配置文件中，打开 enable_cors 配置项（设置为 true）

**Comment by qyazhou** [comment]
已经启动了跨域，目前还是不行，信息如下截图所示。请问还有其他地方需要配置吗？ngix有没有特殊的配置？
服务端
![image](https://github.com/mylxsw/aidea-server/assets/8603086/1c386de4-da34-4c96-869d-8fd87e313825)
客户端：
![image](https://github.com/mylxsw/aidea-server/assets/8603086/45c11243-dad5-4ccf-9c76-811fadef31bf)

**Comment by mylxsw** [comment]
服务端启动命令要把 `--conf config.yaml` 加上去才会读取配置文件，这样

```
go run main.go --conf config.yaml
```

**Comment by qyazhou** [comment]
执行go run main.go --conf config.yaml的时候报了一堆错误，这是数据库没有配好的原因吗？
![image](https://github.com/mylxsw/aidea-server/assets/8603086/09c053fe-7d3a-4f3c-8979-152d815ca044)
