### ISSUE TITLE
讯飞星火一直提示hmac报错？

### ISSUE THREAD

**Issue by oscar810429** [mylxsw/aidea-server#6]
你好，使用一下你的写的这个chatgpt认为挺好的，谢谢分享出来，昨天都搭建好了，就是在讯飞星火一直提示hmac报错？相关接口apikey都成功申请，并且在他们官方测试的代码都可以使用。就是在我们这个代码不能正常使用为什么。

**Comment by mylxsw** [comment]
把错误贴出来看看，还有你的配置，可以打个码，我这边生产的是这样的

<img width="462" alt="image" src="https://github.com/mylxsw/aidea-server/assets/2330911/47b9cf1b-8cc1-4ab5-84fb-2618c7f42987">

**Comment by mylxsw** [comment]
还有就是这个 hmac 生成鉴权信息的时候是用到了当前时间的，检查下当前系统的时间是否正确

<img width="864" alt="image" src="https://github.com/mylxsw/aidea-server/assets/2330911/c64fe03d-ffd4-46cf-b4ec-1dcd9e3c03fe">

**Comment by oscar810429** [comment]
谢谢你的回答。已经找到问题所在了。apikey,apisecret我写反了。自己问题。太感谢你了。
